### ISSUE TITLE
java.lang.UnsupportedOperationException: unsuitable as hash key

### ISSUE THREAD

**Issue by jboyens** [mpeltonen/sbt-idea#1]
When running:
  sbt idea

on:
  sbt 0.7.3
  scala 2.7.7
  sbt-idea-plugin latest snapshot

produces:
java.lang.UnsupportedOperationException: unsuitable as hash key
    at scala.collection.mutable.Buffer$class.hashCode(Buffer.scala:280)
    at scala.collection.mutable.ArrayBuffer.hashCode(ArrayBuffer.scala:26)
    at scala.xml.Utility$.hashCode(Utility.scala:263)
    at scala.xml.Elem.hashCode(Elem.scala:64)
    at scala.collection.mutable.FlatHashTable$class.elemHashCode(FlatHashTable.scala:144)
    at scala.collection.immutable.HashSet.elemHashCode(HashSet.scala:39)
    at scala.collection.mutable.FlatHashTable$class.containsEntry(FlatHashTable.scala:56)
    at scala.collection.immutable.HashSet.containsEntry(HashSet.scala:39)
    at scala.collection.immutable.HashSet.$plus(HashSet.scala:60)
    at scala.collection.immutable.Set$$anonfun$$plus$plus$1.apply(Set.scala:73)
    at scala.collection.immutable.Set$$anonfun$$plus$plus$1.apply(Set.scala:73)
    at scala.Iterator$class.foldLeft(Iterator.scala:520)
    at scala.runtime.BoxedArray$AnyIterator.foldLeft(BoxedArray.scala:45)
    at scala.Iterable$class.foldLeft(Iterable.scala:321)
    at scala.runtime.BoxedArray.foldLeft(BoxedArray.scala:24)
    at scala.Iterable$class.$div$colon(Iterable.scala:338)
    at scala.runtime.BoxedArray.$div$colon(BoxedArray.scala:24)
    at scala.collection.immutable.Set$class.$plus$plus(Set.scala:73)
    at scala.collection.immutable.HashSet.$plus$plus(HashSet.scala:39)
    at scala.collection.immutable.HashSet$.apply(HashSet.scala:26)
    at scala.collection.immutable.Set4.$plus(Set4.scala:31)
    at scala.collection.immutable.Set$$anonfun$map$1.apply(Set.scala:167)
    at scala.collection.immutable.Set$$anonfun$map$1.apply(Set.scala:167)
    at scala.Iterator$class.foldLeft(Iterator.scala:520)
    at scala.collection.mutable.ResizableArray$$anon$1.foldLeft(ResizableArray.scala:66)
    at scala.Iterable$class.foldLeft(Iterable.scala:321)
    at scala.collection.immutable.HashSet.foldLeft(HashSet.scala:39)
    at scala.collection.immutable.Set$class.map(Set.scala:167)
    at scala.collection.immutable.HashSet.map(HashSet.scala:39)
    at IdeaModuleDescriptor.content(IdeaModuleDescriptor.scala:35)
    at SaveableXml$class.save(SaveableXml.scala:10)
    at IdeaModuleDescriptor.save(IdeaModuleDescriptor.scala:4)
    at IdeaPlugin$class.createIdeaProject(IdeaPlugin.scala:11)
    at LDSProject.createIdeaProject(LDSProject.scala:4)
    at IdeaPlugin$$anonfun$idea$1.apply(IdeaPlugin.scala:4)
    at IdeaPlugin$$anonfun$idea$1.apply(IdeaPlugin.scala:4)
    at sbt.TaskManager$Task.invoke(TaskManager.scala:62)
    at sbt.impl.RunTask.doRun$1(RunTask.scala:77)
    at sbt.impl.RunTask.runTask(RunTask.scala:85)
    at sbt.impl.RunTask.run(RunTask.scala:32)
    at sbt.impl.RunTask$.apply(RunTask.scala:17)
    at sbt.impl.RunTask$.apply(RunTask.scala:16)
    at sbt.Project$class.run(Project.scala:98)
    at sbt.Project$class.act(Project.scala:129)
    at sbt.BasicScalaProject.act(DefaultProject.scala:21)
    at LDSProject.act(LDSProject.scala:50001)
    at sbt.xMain$$anonfun$8.apply(Main.scala:487)
    at sbt.xMain$$anonfun$8.apply(Main.scala:487)
    at sbt.xMain.withAction(Main.scala:520)
    at sbt.xMain.sbt$xMain$$handleAction(Main.scala:487)
    at sbt.xMain.handleCommand(Main.scala:477)
    at sbt.xMain.processAction(Main.scala:418)
    at sbt.xMain.process$1(Main.scala:238)
    at sbt.xMain.processArguments(Main.scala:247)
    at sbt.xMain.startProject(Main.scala:105)
    at sbt.xMain.run(Main.scala:82)
    at sbt.xMain.run0$1(Main.scala:33)
    at sbt.xMain.run(Main.scala:40)
    at xsbt.boot.Launch$.run(Launch.scala:51)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:40)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:40)
    at xsbt.boot.Launch$.launch(Launch.scala:55)
    at xsbt.boot.Launch$.explicit(Launch.scala:40)
    at xsbt.boot.Launch$.initialized(Launch.scala:36)
    at xsbt.boot.Launch$.parsed(Launch.scala:31)
    at xsbt.boot.Launch$.configured(Launch.scala:21)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Launch$.apply(Launch.scala:13)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.run(Boot.scala:19)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)

**Comment by mpeltonen** [comment]
Yes, seems easily reproducible. It seems to be sbt 0.7.3 related, with 0.7.2 this does not happen. Thanks for reporting!
