### ISSUE TITLE
the idea project generated by sbt-idea can't compile when using with scala 2.10 because the new version of scala separate some class to a new jar file name scala-reflect.jar

### ISSUE THREAD

**Issue by sparkle** [mpeltonen/sbt-idea#175]
Here's the exception:

Exception in thread "main" java.lang.NoClassDefFoundError: scala/tools/nsc/io/Streamable$Bytes  at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2442)
    at java.lang.Class.getMethod0(Class.java:2685)
    at java.lang.Class.getMethod(Class.java:1620)
    at org.jetbrains.plugins.scala.compiler.rt.ClassRunner.main(ClassRunner.java:45)
Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.io.Streamable$Bytes
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 17 more

Quick fix:
Open Module Settings -> Libraries -> add scala-reflect.jar to the scala version that you use to compile

**Comment by jozic** [comment]
Please try latest snapshot for sbt 0.12
Mikko added a fix for scala 2.10.x here https://github.com/mpeltonen/sbt-idea/commit/b99b66d37cc417acf6204ca11c878e70847e26a0

**Comment by mpeltonen** [comment]
Yeah, the latest snapshot might fix the issue so try that.

**Comment by sparkle** [comment]
Oh I find it, thanks a lot.
