### ISSUE TITLE
Maven URL

### ISSUE THREAD

**Issue by adamstrickland** [mpeltonen/sbt-idea#18]
I was unable to get the SBT processor to work using the repo URL in the README; instead I used

```
*sbtIdeaRaw at http://github.com/mpeltonen/mpeltonen.github.com/raw/master/maven
```

and everything worked fine.  Probably user error, but thought you should know.

**Comment by adamstrickland** [comment]
I also had problems with using the processor; when invoking the processor itself, it threw out:

```
java.lang.NoSuchMethodError: IdeaEnvironment.<init>(Lsbt/Project;)V
at IdeaProcessor.createIdeaProject(IdeaProcessor.scala:26)
at IdeaProcessor.attemptIdeaProject(IdeaProcessor.scala:19)
at IdeaProcessor.apply(IdeaProcessor.scala:12)
at sbt.processor.BasicProcessor.apply(Processor.scala:28)
at sbt.xMain$$anonfun$process$1$7.apply(Main.scala:248)
at sbt.xMain$$anonfun$process$1$7.apply(Main.scala:248)
at sbt.xMain.tryOrFail$1(Main.scala:146)
at sbt.xMain.process$1(Main.scala:247)
at sbt.xMain$Continue$1.apply(Main.scala:132)
at sbt.xMain.run$1(Main.scala:136)
at sbt.xMain.processArguments(Main.scala:266)
at sbt.xMain.startProject(Main.scala:107)
at sbt.xMain.run(Main.scala:84)
at sbt.xMain.run0$1(Main.scala:35)
at sbt.xMain.run(Main.scala:42)
at xsbt.boot.Launch$.run(Launch.scala:53)
at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:42)
at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:42)
at xsbt.boot.Launch$.launch(Launch.scala:57)
at xsbt.boot.Launch$.explicit(Launch.scala:42)
at xsbt.boot.Launch$.initialized(Launch.scala:38)
at xsbt.boot.Launch$.parsed(Launch.scala:31)
at xsbt.boot.Launch$.configured(Launch.scala:21)
at xsbt.boot.Launch$.apply(Launch.scala:16)
at xsbt.boot.Launch$.apply(Launch.scala:13)
at xsbt.boot.Boot$.runImpl(Boot.scala:24)
at xsbt.boot.Boot$.run(Boot.scala:19)
at xsbt.boot.Boot$.main(Boot.scala:15)
at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.NoSuchMethodError: IdeaEnvironment.<init>(Lsbt/Project;)V
```

I'll take a look when/if I get a chance

**Comment by mpeltonen** [comment]
You're right. Plugin download does not currently work for me either. Not even the raw url you suggested. Need to take a deeper look.

**Comment by mpeltonen** [comment]
Hmm. Either there was some problem with gh-pages access yesterday, or deleting ~/.ivy2 helped, but now everything works for me as expected with the original url from readme.

**Comment by mpeltonen** [comment]
Adam: did you resolve these problems, or do they still exist?

**Comment by adamstrickland** [comment]
Mikko: everything looks good now, thanks.

**Comment by adamstrickland** [comment]
Closing

**Comment by wstrange** [comment]
This still is not working for me - looks like something is broken

**Comment by mpeltonen** [comment]
Yes, it looks so. But what it is and how to reproduce? Does running "sbt clean-plugins" and removing ~/.ivy2 folder fix it for you?

**Comment by wstrange** [comment]
No - the issue is that the github maven URL is not there. Try to go to:
http://mpeltonen.github.com/maven/ 
You will see it is not created. 

Also - I am using scala 2.8.0. Does the plugin need to be built against 2.8.0?

**Comment by mpeltonen** [comment]
No, it works, it's just that it does not allow directory listing but that is not needed. You can get the artifacts with direct url, for example http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea-core_2.7.7/0.1-SNAPSHOT/sbt-idea-core_2.7.7-0.1-SNAPSHOT.jar . That's how sbt/ivy/maven access them.

Plugin needs to be built against 2.7.7, sbt does not support 2.8 plugins yet. But that should be taken care of by the project definition/build.properties.

**Comment by wstrange** [comment]
That worked! I was a little consfused on the plugin scala version vs. build scala version. Thanks
