### ISSUE TITLE
NoClassDefFoundError: scala/reflect/internal/Trees in latest 1.2.0 snapshot

### ISSUE THREAD

**Issue by tommcp** [mpeltonen/sbt-idea#187]
With the latest snapshot, I get the following error when I try to compile:
Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/internal/Trees at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2444)
    at java.lang.Class.getMethod0(Class.java:2687)
    at java.lang.Class.getMethod(Class.java:1620)
    at org.jetbrains.plugins.scala.compiler.rt.ClassRunner.main(ClassRunner.java:45)
Caused by: java.lang.ClassNotFoundException: scala.reflect.internal.Trees
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    ... 27 more

I can work around this at the moment by adding ~/.sbt/boot/scala-2.10.0-RC2/lib/scala-reflect.jar to the library for scaka-2.10.0-RC2, but is there any way this can be done when gen-idea is run?

**Comment by mpeltonen** [comment]
Hmm, this should work already. I added scala-reflect.jar a while ago (https://github.com/mpeltonen/sbt-idea/commit/b99b66d37cc417acf6204ca11c878e70847e26a0)

What is your sbt version and scalaVersion for the project?

I've also seen this occasionally and contributed it to currently unknown sbt/ivy caching issue, as I've been able to resolve it by cleaning target directories and/or ivy cache. 

I need to check though that currently deployed snapshot is not somehow broken.

**Comment by tommcp** [comment]
I've just checked out a clean copy of my project, blown away the ivy cache of sbt-idea and re-genned the project, but I'm afraid still have the same issue.

I'm on sbt 0.11.3 and scala 2.10.0-RC2

**Comment by mpeltonen** [comment]
Ah, I had forgotten to backport the fix to 0.11 branch. Just uploaded new snapshot, try if it works for you now?

**Comment by tommcp** [comment]
It took a while for the snapshot to filter through, but it's working perfectly now thanks!

One small point for anyone else - it's best to blow away the old project, as when I tried to re-gen the project it (correctly) added the "SBT: scala:2.10.0-RC2" library, but the project defaulted to the old "scala:2.10.0-RC22" without the reflect jar.

**Comment by mpeltonen** [comment]
Yeah, after library naming change in #183, it is best to do (when Idea is closed) at least 'rm .idea/libraries/*' before gen-idea.

**Comment by jozic** [comment]
I think this should be mentioned in release notes when you cut off a new release. Just to save someone's time
I mean changes in library naming

**Comment by mpeltonen** [comment]
Absolutely!

**Comment by mkhettry** [comment]
I'm continuing to see this error. Environment is 
- IntellijIdea 11.1 Community Edition
- Scala version 2.10.0-RC3
- My .sbt/0.12.1/plugins/build.sbt (I've tried both 1.2.0 and 1.3.0-SNAPSHOT)

resolvers += "sbt-idea-repo" at "http://mpeltonen.github.com/maven/"

resolvers += "Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"

addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.3.0-SNAPSHOT")
- In Project Settings -> Libraries I can see that I have the 2.10.0-RC3 libraries from ~/.sbt/0.12.1/boot/scala-2.10.0-RC3/scala-{library,compiler,reflect}.jar
- In Compiler -> Scala Compiler, I'm set to use Internal FSC compiler 2.10.0-RC3. Any ideas on what I might be missing? here is the complete stack trace

Exception in thread "main" java.lang.NoClassDefFoundError: scala/reflect/io/Streamable$Bytes    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2427)
    at java.lang.Class.getMethod0(Class.java:2670)
    at java.lang.Class.getMethod(Class.java:1603)
    at org.jetbrains.plugins.scala.compiler.rt.ClassRunner.main(ClassRunner.java:45)
Caused by: java.lang.ClassNotFoundException: scala.reflect.io.Streamable$Bytes
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 17 more

**Comment by mpeltonen** [comment]
No immediate guesses what could cause this. I can try the same setup later when I have some time.

What you could do is try Idea 12 and/or Scala 2.10.0 final? Also could try 'rm -rf <project_dir>/.idea*' and 'rm -rf ~/.ivy2' (with Idea closed) before 'sbt gen-idea' and then compile in idea.

**Comment by mkhettry** [comment]
Thanks, that seems to have fixed things.

**Comment by dwijnand** [comment]
I had this issue and the fix for me was to add scala-reflect.jar from within ~/.sbt/boot/scala-2.10.0/lib to the scala-2.10.0 library (not org.scala-lang_scala-library_2.10.0).

**Comment by andychase** [comment]
@mpeltonen @mkhettry This worked for me as well
