### ISSUE TITLE
Unresolved dependency Android

### ISSUE THREAD

**Issue by PhilAndrew** [mpeltonen/sbt-idea#229]
orsamac:neptune_scala orsa$ sbt gen-idea
[info] Loading project definition from /Users/orsa/home/projects/neptune_scala/project
[info] Updating {file:/Users/orsa/home/projects/neptune_scala/project/}default-de416c...
[info] Resolving org.scala-sbt#precompiled-2_10_0;0.12.2 ...
[info] Done updating.
[info] Set current project to neptune (in build file:/Users/orsa/home/projects/neptune_scala/)
[info] Creating IDEA module for project 'language' ...
[info] Resolving org.scala-lang#scala-library;2.10.0 ...
[info] Creating IDEA module for project 'parent' ...
[info] Resolving org.scala-lang#scala-library;2.10.0 ...
[info] Creating IDEA module for project 'ui' ...
[info] Resolving org.scala-lang#scala-library;2.10.0 ...
[info] Excluding folder target
[info] Created /Users/orsa/home/projects/neptune_scala/.idea/IdeaProject.iml
[info] Created /Users/orsa/home/projects/neptune_scala/.idea
[info] Excluding folder /Users/orsa/home/projects/neptune_scala/language/target
[info] Created /Users/orsa/home/projects/neptune_scala/.idea_modules/language.iml
[info] Excluding folder /Users/orsa/home/projects/neptune_scala/target
[info] Created /Users/orsa/home/projects/neptune_scala/.idea_modules/parent.iml
[info] Excluding folder /Users/orsa/home/projects/neptune_scala/ui/target
[info] Created /Users/orsa/home/projects/neptune_scala/.idea_modules/ui.iml
[info] Created /Users/orsa/home/projects/neptune_scala/.idea_modules/language-build.iml
[info] Created /Users/orsa/home/projects/neptune_scala/.idea_modules/parent-build.iml
[info] Created /Users/orsa/home/projects/neptune_scala/.idea_modules/ui-build.iml
orsamac:neptune_scala orsa$ sbt clean
[info] Loading project definition from /Users/orsa/home/projects/neptune_scala/project
[info] Updating {file:/Users/orsa/home/projects/neptune_scala/project/}default-de416c...
[info] Resolving org.scala-sbt#sbt-android-plugin;0.6.3-20130429-SNAPSHOT ...
 update
[warn]  module not found: org.scala-sbt#sbt-android-plugin;0.6.3-20130429-SNAPSHOT
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-android-plugin/scala_2.9.2/sbt_0.12/0.6.3-20130429-SNAPSHOT/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/org.scala-sbt/sbt-android-plugin/scala_2.9.2/sbt_0.12/0.6.3-20130429-SNAPSHOT/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/orsa/.ivy2/local/org.scala-sbt/sbt-android-plugin/scala_2.9.2/sbt_0.12/0.6.3-20130429-SNAPSHOT/ivys/ivy.xml
[warn] ==== Sonatype snapshots: tried
[warn]   http://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/sbt-android-plugin_2.9.2_0.12/0.6.3-20130429-SNAPSHOT/sbt-android-plugin-0.6.3-20130429-SNAPSHOT.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/scala-sbt/sbt-android-plugin_2.9.2_0.12/0.6.3-20130429-SNAPSHOT/sbt-android-plugin-0.6.3-20130429-SNAPSHOT.pom
[info] Resolving org.scala-sbt#precompiled-2_10_0;0.12.2 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-sbt#sbt-android-plugin;0.6.3-20130429-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      org.scala-sbt:sbt-android-plugin:0.6.3-20130429-SNAPSHOT (sbtVersion=0.12, scalaVersion=2.9.2)
[warn] 
sbt.ResolveException: unresolved dependency: org.scala-sbt#sbt-android-plugin;0.6.3-20130429-SNAPSHOT: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:214)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:102)
    at sbt.IvySbt.liftedTree1$1(Ivy.scala:49)
    at sbt.IvySbt.action$1(Ivy.scala:49)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:58)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:75)
    at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:79)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
    at xsbt.boot.Locks$.apply0(Locks.scala:30)
    at xsbt.boot.Locks$.apply(Locks.scala:27)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:58)
    at sbt.IvySbt.withIvy(Ivy.scala:99)
    at sbt.IvySbt.withIvy(Ivy.scala:95)
    at sbt.IvySbt$Module.withModule(Ivy.scala:114)
    at sbt.IvyActions$.update(IvyActions.scala:121)
    at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:951)
    at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:949)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:972)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:970)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:974)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:969)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:977)
    at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:856)
    at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:853)
    at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
    at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
[error](*:update) sbt.ResolveException: unresolved dependency: org.scala-sbt#sbt-android-plugin;0.6.3-20130429-SNAPSHOT: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? sbt update

**Comment by mpeltonen** [comment]
This should not occur anymore with 1.5.1 or 1.6.0-SNAPSHOT.
