### ISSUE TITLE
java.nio.charset.UnmappableCharacterException on 1.7.0-SNAPSHOT using Scala 2.11.0-M8 and Java 8 on OS X

### ISSUE THREAD

**Issue by boxsterman** [mpeltonen/sbt-idea#279]
The reason for that exception was the default encoding in xml.XML.encoding (ISO-8859-1) that is used in OutputUtil.

```
val w = Channels.newWriter(fos.getChannel(), XML.encoding)
```

Changing it to "UTF-8" instead solved the issue for me locally:

```
val w = Channels.newWriter(fos.getChannel(), "UTF-8")
```

Since the resulting xml files do not contain a dedicated encoding directive, this solution should be generally ok.

Cheers,
Carsten

java.nio.charset.UnmappableCharacterException: Input length = 1
    at java.nio.charset.CoderResult.throwException(CoderResult.java:282)
    at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:285)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135)
    at java.io.Writer.write(Writer.java:157)
    at org.sbtidea.OutputUtil$$anonfun$saveFile$2.apply$mcV$sp(IdeaProjectDescriptor.scala:25)
    at org.sbtidea.OutputUtil$$anonfun$saveFile$2.apply(IdeaProjectDescriptor.scala:25)
    at org.sbtidea.OutputUtil$$anonfun$saveFile$2.apply(IdeaProjectDescriptor.scala:25)
    at scala.util.control.Exception$Catch.apply(Exception.scala:102)
    at org.sbtidea.OutputUtil$.saveFile(IdeaProjectDescriptor.scala:24)
    at org.sbtidea.SaveableXml$class.save(SaveableXml.scala:26)
    at org.sbtidea.IdeaModuleDescriptor.save(IdeaModuleDescriptor.scala:15)
    at org.sbtidea.SbtIdeaPlugin$$anonfun$doCommand$1.apply(SbtIdeaPlugin.scala:115)
    at org.sbtidea.SbtIdeaPlugin$$anonfun$doCommand$1.apply(SbtIdeaPlugin.scala:113)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at org.sbtidea.SbtIdeaPlugin$.doCommand(SbtIdeaPlugin.scala:113)
    at org.sbtidea.SbtIdeaPlugin$$anonfun$org$sbtidea$SbtIdeaPlugin$$ideaCommand$2.apply(SbtIdeaPlugin.scala:45)
    at org.sbtidea.SbtIdeaPlugin$$anonfun$org$sbtidea$SbtIdeaPlugin$$ideaCommand$2.apply(SbtIdeaPlugin.scala:45)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
    at sbt.Command$.process(Command.scala:95)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
    at sbt.State$$anon$1.process(State.scala:179)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.MainLoop$.next(MainLoop.scala:100)
    at sbt.MainLoop$.run(MainLoop.scala:93)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
    at sbt.Using.apply(Using.scala:25)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
    at sbt.MainLoop$.runLogged(MainLoop.scala:25)
    at sbt.StandardMain$.runManaged(Main.scala:57)
    at sbt.xMain.run(Main.scala:29)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
    at xsbt.boot.Launch$.run(Launch.scala:57)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:65)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:32)
    at xsbt.boot.Boot$.main(Boot.scala:21)
    at xsbt.boot.Boot.main(Boot.scala)
[error] java.nio.charset.UnmappableCharacterException:

**Comment by jpsacha** [comment]
I am getting similar error on Windows when I try to use 'gen-idea', but it does not matter which version of Java (7 or 8) or Scala (2.10 or 2.11) I am using. I am also not able to import that simple project in IDEA using its SBT import. The issue is reported here:
http://youtrack.jetbrains.com/issue/SCL-6676
A sample project is attached there.
