### ISSUE TITLE
Using sbt as processor fails due to missing dependency

### ISSUE THREAD

**Issue by afwlehmann** [mpeltonen/sbt-idea#51]
Hi,

apparently the URL that is stated in the documentation isn't applicable anymore? Thanks for looking into this.

<pre>
> *sbtIdeaRepo at http://mpeltonen.github.com/maven/    
[info] Defined new processor repository 'sbtIdeaRepo at http://mpeltonen.github.com/maven/'
> *idea is com.github.mpeltonen sbt-idea-processor 0.4.0
[warn]  module not found: com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0
[warn] ==== local: tried
[warn]   /Users/alex/.ivy2/local/com.github.mpeltonen/sbt-idea-processor_2.8.1/0.4.0/ivys/ivy.xml
[warn]   -- artifact com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0!sbt-idea-processor_2.8.1.jar:
[warn]   /Users/alex/.ivy2/local/com.github.mpeltonen/sbt-idea-processor_2.8.1/0.4.0/jars/sbt-idea-processor_2.8.1.jar
[warn] ==== sbtIdeaRepo: tried
[warn]   http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.pom
[warn]   -- artifact com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0!sbt-idea-processor_2.8.1.jar:
[warn]   http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.jar
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.pom
[warn]   -- artifact com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0!sbt-idea-processor_2.8.1.jar:
[warn]   http://repo1.maven.org/maven2/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.jar
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.pom
[warn]   -- artifact com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0!sbt-idea-processor_2.8.1.jar:
[warn]   http://scala-tools.org/repo-releases/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] 
[warn] :: problems summary ::
[warn] :::: WARNINGS
[warn]      module not found: com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0
[warn]  ==== local: tried
[warn]    /Users/alex/.ivy2/local/com.github.mpeltonen/sbt-idea-processor_2.8.1/0.4.0/ivys/ivy.xml
[warn]    -- artifact com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0!sbt-idea-processor_2.8.1.jar:
[warn]    /Users/alex/.ivy2/local/com.github.mpeltonen/sbt-idea-processor_2.8.1/0.4.0/jars/sbt-idea-processor_2.8.1.jar
[warn]  ==== sbtIdeaRepo: tried
[warn]    http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.pom
[warn]    -- artifact com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0!sbt-idea-processor_2.8.1.jar:
[warn]    http://mpeltonen.github.com/maven/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.jar
[warn]  ==== public: tried
[warn]    http://repo1.maven.org/maven2/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.pom
[warn]    -- artifact com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0!sbt-idea-processor_2.8.1.jar:
[warn]    http://repo1.maven.org/maven2/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.jar
[warn]  ==== Scala-Tools Maven2 Repository: tried
[warn]    http://scala-tools.org/repo-releases/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.pom
[warn]    -- artifact com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0!sbt-idea-processor_2.8.1.jar:
[warn]    http://scala-tools.org/repo-releases/com/github/mpeltonen/sbt-idea-processor_2.8.1/0.4.0/sbt-idea-processor_2.8.1-0.4.0.jar
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      ::          UNRESOLVED DEPENDENCIES         ::
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      :: com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0: not found
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[info] 
[info] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
sbt.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:130)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:112)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:110)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:93)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:93)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:85)
    at sbt.IvySbt.liftedTree1$1(Ivy.scala:41)
    at sbt.IvySbt.action$1(Ivy.scala:41)
    at sbt.IvySbt$$anon$1.call(Ivy.scala:50)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:63)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:67)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:67)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:67)
    at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:45)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:45)
    at xsbt.boot.Locks$.apply(Locks.scala:31)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:50)
    at sbt.IvySbt.withIvy(Ivy.scala:82)
    at sbt.IvySbt$Module.withModule(Ivy.scala:93)
    at sbt.IvyActions$.update(IvyActions.scala:110)
    at sbt.processor.Retrieve$$anonfun$retrieve$1.apply(Retrieve.scala:21)
    at sbt.processor.Retrieve$$anonfun$retrieve$1.apply(Retrieve.scala:21)
    at sbt.processor.Callable$$anon$1.call(Retrieve.scala:31)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:63)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:67)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:67)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:67)
    at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:45)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:45)
    at xsbt.boot.Locks$.apply(Locks.scala:31)
    at sbt.processor.Retrieve.retrieve(Retrieve.scala:21)
    at sbt.processor.ManagerImpl.sbt$processor$ManagerImpl$$retrieveProcessor(Manager.scala:61)
    at sbt.processor.ManagerImpl.defineProcessor(Manager.scala:40)
    at sbt.processor.Execute.apply(Execute.scala:16)
    at sbt.processor.CommandRunner.apply(CommandRunner.scala:13)
    at sbt.xMain$$anonfun$process$1$6.apply(Main.scala:242)
    at sbt.xMain$$anonfun$process$1$6.apply(Main.scala:241)
    at sbt.xMain.tryOrFail$1(Main.scala:146)
    at sbt.xMain.process$1(Main.scala:241)
    at sbt.xMain$Continue$1.apply(Main.scala:132)
    at sbt.xMain.run$1(Main.scala:136)
    at sbt.xMain.processArguments(Main.scala:266)
    at sbt.xMain.startProject(Main.scala:107)
    at sbt.xMain.run(Main.scala:84)
    at sbt.xMain.run0$1(Main.scala:35)
    at sbt.xMain.run(Main.scala:42)
    at xsbt.boot.Launch$.run(Launch.scala:53)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:42)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:42)
    at xsbt.boot.Launch$.launch(Launch.scala:57)
    at xsbt.boot.Launch$.explicit(Launch.scala:42)
    at xsbt.boot.Launch$.initialized(Launch.scala:38)
    at xsbt.boot.Launch$.parsed(Launch.scala:31)
    at xsbt.boot.Launch$.configured(Launch.scala:21)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Launch$.apply(Launch.scala:13)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.run(Boot.scala:19)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
[error] sbt.ResolveException: unresolved dependency: com.github.mpeltonen#sbt-idea-processor_2.8.1;0.4.0: not found
</pre>

**Comment by mpeltonen** [comment]
It looks like you're using Scala 2.8.1 for project definition (def.scala.version=2.8.1 in project/build.properties)?. Sbt 0.7.x and sbt-idea only supports 2.7.7 for project definition. 

Try changing def.scala.version=2.7.7 (or removing it altogether) from build.properties. If you don't have it ot it is 2.7.7, then we'll have to find some other reason for this :)

**Comment by afwlehmann** [comment]
That's it. Thank you so much!
