### ISSUE TITLE
Library paths too aggressively filtered between dependent sub-projects

### ISSUE THREAD

**Issue by rjmac** [mpeltonen/sbt-idea#52]
I have a multi-module project in which there is one project ("Library") that is depended upon by another project ("User").  "Library" depends on a third-party library for its tests, and "User" on the same library for everything.  Rather like this:

``` scala
import sbt._

class Simple(info: ProjectInfo) extends ParentProject(info) with IdeaProject {
  val slf4jVersion = "1.6.1"

  val libraryProject = project("library", "library", new Library(_))
  val userProject = project("user", "user", new User(_), libraryProject)

  class Library(info: ProjectInfo) extends DefaultProject(info) with IdeaProject {
    val slf4j = "org.slf4j" % "slf4j-api" % slf4jVersion % "test->default"
  }

  class User(info: ProjectInfo) extends DefaultProject(info) with IdeaProject {
    val slf4j = "org.slf4j" % "slf4j-api" % slf4jVersion
  }
}
```

The generated IML file for the User project does not contain the declared library as a dependency.

**Comment by mpeltonen** [comment]
Ah, this might be a special case related to #50, when you have the same dependency as compile _and_ transitive test dependency. Thanks for reporting!

**Comment by mpeltonen** [comment]
Just to make sure, is this actually a problem in Idea? I.e. the test-scoped dependency is not seen by the non-test classes of User project in Idea?

**Comment by mpeltonen** [comment]
I think this shouldn't be an issue(?). I just tested in idea, and "Test" scope does not prevent a dependency from not being seen by production code in dependent project. Only if I removed "Exported" -flag, then the dependent module did not compile. Or am I missing something?

**Comment by rjmac** [comment]
They are seen in the IDE itself, but not while running.  So for example, if this is in user/src/main/scala/Main.scala:

``` scala
object Main {
  val log = org.slf4j.LoggerFactory.getLogger(getClass)

  def main(args: Array[String]) {
    log.info("Hello world")
  }
}
```

then there are no red squigglies, and SBT compiles it too of course, but when it comes time to run:

```
/usr/lib/jvm/java-6-openjdk/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:38881,suspend=y,server=n -javaagent:/home/robertm/idea-IC-103.255/plugins/Groovy/lib/agent/gragent.jar -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-6-openjdk/jre/lib/charsets.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/rhino.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/rt.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/jsse.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/jce.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/management-agent.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/resources.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/javazic.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/compilefontconfig.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/about.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/ext/pulse-java.jar:/usr/lib/jvm/java-6-openjdk/jre/lib/ext/dnsns.jar:/usr/share/java/gnome-java-bridge.jar:/home/robertm/simple/user/target/scala_2.8.1/classes:/home/robertm/simple/project/boot/scala-2.8.1/lib/scala-compiler.jar:/home/robertm/simple/project/boot/scala-2.8.1/lib/scala-library.jar:/home/robertm/simple/library/target/scala_2.8.1/classes:/home/robertm/idea-IC-103.255/lib/idea_rt.jar Main
Connected to the target VM, address: '127.0.0.1:38881', transport: 'socket'
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
    at Main$.<init>(Main.scala:10)
    at Main$.<clinit>(Main.scala)
    at Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    ... 3 more
Disconnected from the target VM, address: '127.0.0.1:38881', transport: 'socket'

Process finished with exit code 1
```

Comment out the dependency in the Library project, reload/update/idea, and it runs fine.

**Comment by mpeltonen** [comment]
Ok, so the scope affects runtime classpath, like it obviously should. Good enough reason to fix it :) Thanks!

**Comment by mpeltonen** [comment]
Could you test 0.5.0-SNAPSHOT, if it fixes the issue for you?

**Comment by rjmac** [comment]
I can, and it did.  Thanks!
