### ISSUE TITLE
stackoverflow on creating idea files

### ISSUE THREAD

**Issue by robb1e** [mpeltonen/sbt-idea#57]
Hello, I've got a SBT project which has created idea files previously, but when I've updated and re-run I'm getting this error:

Any ideas?

java.lang.StackOverflowError
    at scala.collection.mutable.HashTable$class.elemHashCode(HashTable.scala:154)
    at scala.collection.mutable.HashMap.elemHashCode(HashMap.scala:33)
    at scala.collection.mutable.HashTable$class.findEntry(HashTable.scala:66)
    at scala.collection.mutable.HashMap.findEntry(HashMap.scala:33)
    at scala.collection.mutable.HashMap.findEntry(HashMap.scala:33)
    at scala.collection.mutable.DefaultMapModel$class.update(DefaultMapModel.scala:38)
    at scala.collection.mutable.HashMap.update(HashMap.scala:33)
    at sbt.Reflective$$anonfun$reflectiveMappings$1.apply(BasicProjectTypes.scala:574)
    at sbt.Reflective$$anonfun$reflectiveMappings$1.apply(BasicProjectTypes.scala:573)
    at scala.collection.mutable.OpenHashMap$$anonfun$foreach$1.apply(OpenHashMap.scala:197)
    at scala.collection.mutable.OpenHashMap$$anonfun$foreach$1.apply(OpenHashMap.scala:195)
    at scala.collection.mutable.OpenHashMap$$anonfun$foreachUndeletedEntry$1.apply(OpenHashMap.scala:202)
    at scala.collection.mutable.OpenHashMap$$anonfun$foreachUndeletedEntry$1.apply(OpenHashMap.scala:202)
    at scala.Iterator$class.foreach(Iterator.scala:414)
    at scala.runtime.BoxedArray$AnyIterator.foreach(BoxedArray.scala:45)
    at scala.Iterable$class.foreach(Iterable.scala:256)
    at scala.runtime.BoxedArray.foreach(BoxedArray.scala:24)
    at scala.collection.mutable.OpenHashMap.foreachUndeletedEntry(OpenHashMap.scala:202)
    at scala.collection.mutable.OpenHashMap.foreach(OpenHashMap.scala:195)
    at sbt.Reflective$.reflectiveMappings(BasicProjectTypes.scala:573)
    at sbt.ReflectiveModules$class.reflectiveModuleMappings(BasicProjectTypes.scala:551)
    at sbt.BasicScalaProject.reflectiveModuleMappings(DefaultProject.scala:21)
    at sbt.ReflectiveModules$class.subProjects(BasicProjectTypes.scala:550)
    at sbt.BasicScalaProject.subProjects(DefaultProject.scala:21)
    at IdeaProcessor.attemptIdeaProject(IdeaProcessor.scala:16)
    at IdeaProcessor$$anonfun$attemptIdeaProject$1.apply(IdeaProcessor.scala:16)
    at IdeaProcessor$$anonfun$attemptIdeaProject$1.apply(IdeaProcessor.scala:16)
    at scala.Iterator$class.foreach(Iterator.scala:414)

then these lines repeat over and over.

```
at IdeaProcessor.attemptIdeaProject(IdeaProcessor.scala:16)
at IdeaProcessor$$anonfun$attemptIdeaProject$1.apply(IdeaProcessor.scala:16)
at IdeaProcessor$$anonfun$attemptIdeaProject$1.apply(IdeaProcessor.scala:16)
at scala.Iterator$class.foreach(Iterator.scala:414)
```

**Comment by robb1e** [comment]
Turns out it might be a conflict with a withsources plugin, https://github.com/OlegYch/sbt-sources-plugin

Removing this got rid of this error.

**Comment by OlegYch** [comment]
@robb1e can you please elaborate on how you get rid of this error, i am getting it even if i remove sbt-sources processor and do full clean

**Comment by robb1e** [comment]
I initially had it as a mixin in my sbt project file, so I got rid of that and just installed it as a processor according to the instructions on it's github page.  Then after a clean it seemed to work.  I didn't do anything special to get rid of it.  

Still having trouble there?

**Comment by OlegYch** [comment]
i'm having this exception with this project https://github.com/OlegYch/scalabot
using sbt-idea-processor 0.4.0
not using any other processors or plugins...
