### ISSUE TITLE
Nullpointer exception

### ISSUE THREAD

**Issue by rparree** [mpeltonen/sbt-idea#9]
Did 

1) git clone git://github.com/ghostm/lift_sbt_prototype.git demo2
2) followed instructions on this site
3) got a nullpointer exception

Version information
[info] Building project Lift SBT Tempalte 0.1 against Scala 2.8.0
[info]    using LiftProject with sbt 0.7.4 and Scala 2.7.7

Stacktrace after issuing idea command
java.lang.NullPointerException
        at scala.xml.XML$.saveFull(XML.scala:138)
        at scala.xml.XML$.save(XML.scala:103)
        at scala.xml.XML$.save(XML.scala:93)
        at SaveableXml$class.save(SaveableXml.scala:10)
        at IdeaModuleDescriptor.save(IdeaModuleDescriptor.scala:5)
        at IdeaProject$class.createIdeaProject(IdeaProject.scala:15)
        at LiftProject$$anonfun$subProject$1$$anon$1.createIdeaProject(LiftProject.scala:12)
        at IdeaProject$$anonfun$idea$1.apply(IdeaProject.scala:6)
        at IdeaProject$$anonfun$idea$1.apply(IdeaProject.scala:6)
        at sbt.TaskManager$Task.invoke(TaskManager.scala:62)
        at sbt.impl.RunTask.doRun$1(RunTask.scala:77)
        at sbt.impl.RunTask.runTask(RunTask.scala:85)
        at sbt.impl.RunTask.sbt$impl$RunTask$$runIfNotRoot(RunTask.scala:60)
        at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
        at sbt.impl.RunTask$$anonfun$runTasksExceptRoot$2.apply(RunTask.scala:48)
        at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
        at sbt.Distributor$Run$Worker$$anonfun$2.apply(ParallelRunner.scala:131)
        at sbt.Control$.trapUnit(Control.scala:19)
        at sbt.Distributor$Run$Worker.run(ParallelRunner.scala:131)

**Comment by mpeltonen** [comment]
Hmm, worked for me:

<pre>
mpe@L229:~/git/demo2 master$ sbt idea
[info] Building project Lift SBT Tempalte 0.1 against Scala 2.8.0
[info]    using LiftProject with sbt 0.7.4 and Scala 2.7.7
[info] 
[info] == idea ==
[info] Created /home/mpe/git/demo2/Lift SBT Tempalte.ipr
[info] Created /home/mpe/git/demo2/project/sbt_project_definition.iml
[info] Created /home/mpe/git/demo2/Lift SBT Tempalte.iml
[info] == idea ==
[success] Successful.
[info] 
[info] Total time: 0 s, completed Aug 10, 2010 1:33:23 PM
[info] 
[info] Total session time: 1 s, completed Aug 10, 2010 1:33:23 PM
[success] Build completed successfully.
</pre>

Did you run "sbt update" before "sbt idea" (don't know if that even could be the cause, but just tu be sure)?

**Comment by mpeltonen** [comment]
What does "java -version" say?

**Comment by rparree** [comment]
java version "1.6.0_20"
Java(TM) SE Runtime Environment (build 1.6.0_20-b02)
Java HotSpot(TM) Server VM (build 16.3-b01, mixed mode)

**Comment by mpeltonen** [comment]
Ok, the same as I do. Just thought to ask because the NPE seems to be in an interesting line (XML.scala:138): http://lampsvn.epfl.ch/trac/scala/browser/scala/tags/R_2_7_7_final/src/library/scala/xml/XML.scala?view=markup#L138

**Comment by rparree** [comment]
I will remote debug and see what the values are there

**Comment by rparree** [comment]
hmmm during remote debugging it works... (race condition?)

Then removed the generated idea files and rerun to get the same exception

**Comment by rparree** [comment]
still the same behaviour:
1) With remote debugging it works
2) runing without debugging it ends with nullpointer exception

found out if  first do 
mkdir subproject/

and then run, it works

**Comment by mpeltonen** [comment]
Cool, a heisenbug :)

**Comment by karianne** [comment]
I got the same error when I included 
    lazy val subProject = project("subproject", "subproject", new DefaultProject(_) with IdeaProject)
in my non-multimodule project. This happens when you start with a very simple scala project and just copy paste the SBT setup from the usage instructions. Perhaps it should be clearer that that particular line only applias for multi-module builds?

**Comment by mpeltonen** [comment]
Teigen's recent commit included a fix into this, i.e. now xml is saved only if parent directory exists.

But you're right, instructions need clarification too.

**Comment by mpeltonen** [comment]
I improved setup instructions a bit. I hope it's more clear now?

**Comment by karianne** [comment]
Much better!
